sudo: false

language: php

dist: trusty

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

before_script:
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then composer require satooshi/php-coveralls:1.* -n ; fi
  - if [[ "$TRAVIS_PHP_VERSION" != '7.1' ]]; then composer install -n ; fi

script:
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then vendor/bin/phpunit --coverage-clover clover.xml ; fi
  - if [[ "$TRAVIS_PHP_VERSION" != '7.1' ]]; then vendor/bin/phpunit ; fi

after_script:
- if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then php vendor/bin/coveralls --coverage_clover=clover.xml -v ; fi
